create extension if not exists pgcrypto;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text, role text not null default 'learner',
 target_band numeric(2,1) default 8.0, daily_minutes int default 30,
 current_lesson int default 1, total_xp int default 0, coins int default 0,
 hearts int default 5, streak_days int default 0, placement_completed boolean default false,
 onboarding_completed boolean default false, created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.courses(
 id bigint generated by default as identity primary key,
 slug text unique not null, title text not null, title_vi text, description text, description_vi text,
 is_published boolean default true, created_at timestamptz default now()
);

create table if not exists public.lessons(
 id bigint generated by default as identity primary key,
 course_id bigint references public.courses(id) on delete cascade,
 level_number int unique not null check(level_number between 1 and 100),
 slug text unique not null, title text not null, title_vi text, subtitle text, subtitle_vi text,
 stage_number int not null, stage_name text not null, cefr_level text not null,
 xp_reward int default 100, coin_reward int default 20, estimated_minutes int default 40,
 is_checkpoint boolean default false, is_published boolean default true,
 created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.lesson_blocks(
 id bigint generated by default as identity primary key,
 lesson_id bigint not null references public.lessons(id) on delete cascade,
 block_type text not null, title text, title_vi text, instructions text, instructions_vi text,
 content jsonb not null default '{}'::jsonb, position int not null default 0,
 is_required boolean default true, is_published boolean default true,
 unique(lesson_id,position)
);

create table if not exists public.question_banks(
 id bigint generated by default as identity primary key,
 slug text unique not null, title text not null, purpose text, tags text[] default '{}',
 created_at timestamptz default now()
);

create table if not exists public.questions(
 id bigint generated by default as identity primary key,
 bank_id bigint references public.question_banks(id) on delete cascade,
 question_type text not null, skill text, difficulty int default 1,
 prompt text not null, prompt_vi text, options jsonb default '[]'::jsonb,
 correct_answer jsonb, explanation text, explanation_vi text,
 audio_url text, audio_text text, metadata jsonb default '{}'::jsonb,
 created_at timestamptz default now()
);

create table if not exists public.placement_attempts(
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 score int, total_questions int, recommended_level int,
 estimated_cefr text, estimated_ielts text, skill_profile jsonb default '{}'::jsonb,
 created_at timestamptz default now()
);

create table if not exists public.user_progress(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 level_id int not null, completed boolean default false, score numeric(5,2),
 earned_xp int default 0, earned_coins int default 0,
 completed_at timestamptz, updated_at timestamptz default now(),
 unique(user_id,level_id)
);

create table if not exists public.game_sessions(
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 game_slug text not null, level_number int, score int default 0, gates_passed int default 0,
 questions_answered int default 0, correct_answers int default 0,
 xp_earned int default 0, coins_earned int default 0, created_at timestamptz default now()
);

create table if not exists public.ielts_papers(
 id bigint generated by default as identity primary key,
 slug text unique not null, title text not null, module text not null,
 test_type text default 'academic', duration_minutes int not null,
 instructions text, metadata jsonb default '{}'::jsonb, is_published boolean default true,
 created_at timestamptz default now()
);

create table if not exists public.ielts_sections(
 id bigint generated by default as identity primary key,
 paper_id bigint not null references public.ielts_papers(id) on delete cascade,
 section_number int not null, title text, passage text, audio_url text, transcript text,
 instructions text, metadata jsonb default '{}'::jsonb,
 unique(paper_id,section_number)
);

create table if not exists public.ielts_items(
 id bigint generated by default as identity primary key,
 section_id bigint not null references public.ielts_sections(id) on delete cascade,
 item_number int not null, question_type text not null, prompt text not null,
 options jsonb default '[]'::jsonb, correct_answer jsonb, explanation text,
 metadata jsonb default '{}'::jsonb, unique(section_id,item_number)
);

create table if not exists public.ielts_attempts(
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 paper_id bigint references public.ielts_papers(id) on delete cascade,
 answers jsonb default '{}'::jsonb, flagged_items jsonb default '[]'::jsonb,
 score numeric(5,2), started_at timestamptz default now(), submitted_at timestamptz
);
