-- NEXORA V2 — CORE DATABASE SCHEMA
-- Run first in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  target_band numeric(2,1) not null default 8.0,
  daily_minutes integer not null default 30 check (daily_minutes between 5 and 300),
  current_lesson integer not null default 1 check (current_lesson between 1 and 100),
  total_xp integer not null default 0 check (total_xp >= 0),
  streak_days integer not null default 0 check (streak_days >= 0),
  onboarding_completed boolean not null default false,
  role text not null default 'learner' check (role in ('learner','editor','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  level_number integer not null unique check (level_number between 1 and 100),
  slug text not null unique,
  title text not null,
  subtitle text,
  stage_number integer not null check (stage_number between 1 and 10),
  stage_name text not null,
  cefr_level text not null,
  estimated_minutes integer not null default 25 check (estimated_minutes > 0),
  xp_reward integer not null default 80 check (xp_reward >= 0),
  is_checkpoint boolean not null default false,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_sections (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  section_type text not null check (
    section_type in ('overview','vocabulary','grammar','reading','listening','speaking','writing','quiz')
  ),
  title text,
  instructions text,
  content jsonb not null default '{}'::jsonb,
  position integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (lesson_id, section_type)
);

create table if not exists public.lesson_questions (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  section_id bigint references public.lesson_sections(id) on delete cascade,
  question_type text not null default 'multiple_choice' check (
    question_type in ('multiple_choice','true_false','short_answer','matching')
  ),
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_answer jsonb not null default 'null'::jsonb,
  explanation text,
  position integer not null default 0,
  points integer not null default 1 check (points > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  level_id integer not null check (level_id between 1 and 100),
  completed boolean not null default false,
  earned_xp integer not null default 0 check (earned_xp >= 0),
  score numeric(5,2),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, level_id)
);

create table if not exists public.user_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  question_id bigint not null references public.lesson_questions(id) on delete cascade,
  answer jsonb not null,
  is_correct boolean,
  points_awarded integer not null default 0,
  answered_at timestamptz not null default now(),
  unique (user_id, question_id)
);

create table if not exists public.vocabulary_items (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  word text not null,
  pronunciation text,
  meaning text not null,
  example text,
  audio_url text,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.user_vocabulary (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  vocabulary_id bigint not null references public.vocabulary_items(id) on delete cascade,
  mastery_level integer not null default 0 check (mastery_level between 0 and 5),
  next_review_at timestamptz,
  last_reviewed_at timestamptz,
  review_count integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, vocabulary_id)
);

create table if not exists public.achievements (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text not null,
  icon text,
  xp_reward integer not null default 0,
  condition_type text not null,
  condition_value integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id bigint not null references public.achievements(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  unique (user_id, achievement_id)
);

create index if not exists lessons_level_number_idx on public.lessons(level_number);
create index if not exists lesson_sections_lesson_position_idx on public.lesson_sections(lesson_id, position);
create index if not exists lesson_questions_lesson_position_idx on public.lesson_questions(lesson_id, position);
create index if not exists user_progress_user_idx on public.user_progress(user_id);
create index if not exists vocabulary_items_lesson_idx on public.vocabulary_items(lesson_id);
create index if not exists user_vocabulary_review_idx on public.user_vocabulary(user_id, next_review_at);
