create table if not exists public.placement_blueprints(
 id bigint generated by default as identity primary key,
 slug text unique not null,
 title text not null,
 config jsonb not null,
 is_active boolean default true,
 created_at timestamptz default now()
);

insert into public.placement_blueprints(slug,title,config)
values(
 'nexora-placement-v1',
 'Nexora Four-Skill Placement V1',
 '{
   "total_questions":40,
   "skills":{
     "grammar":{"count":12,"weight":0.25},
     "vocabulary":{"count":10,"weight":0.20},
     "reading":{"count":10,"weight":0.30},
     "listening":{"count":8,"weight":0.25}
   },
   "difficulty_bands":[1,2,3,4],
   "thresholds":[
     {"min":0.88,"cefr":"C1","ielts":"7.0-8.0","start_level":71},
     {"min":0.74,"cefr":"B2","ielts":"5.5-6.5","start_level":56},
     {"min":0.58,"cefr":"B1","ielts":"4.5-5.0","start_level":36},
     {"min":0.42,"cefr":"A2","ielts":"3.5-4.0","start_level":21},
     {"min":0.25,"cefr":"A1","ielts":"3.0-3.5","start_level":11},
     {"min":0.00,"cefr":"Pre-A1","ielts":"Below 3.5","start_level":1}
   ]
 }'::jsonb
)
on conflict(slug) do update set config=excluded.config;

alter table public.placement_blueprints enable row level security;
create policy "read active placement blueprints" on public.placement_blueprints for select using(is_active=true);
notify pgrst,'reload schema';
