create table if not exists public.ielts_test_suites(
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  source_filename text,
  status text not null default 'draft' check(status in ('draft','review','published','archived')),
  created_by uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.ielts_papers
  add column if not exists suite_id bigint references public.ielts_test_suites(id) on delete cascade,
  add column if not exists status text not null default 'draft'
    check(status in ('draft','review','published','archived')),
  add column if not exists created_by uuid references auth.users(id) on delete set null;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.profiles
    where id=auth.uid() and role in ('admin','founder')
  );
$$;

create or replace function public.admin_import_ielts_bundle_json(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  suite_payload jsonb;
  paper_payload jsonb;
  suite_pk bigint;
  paper_pk bigint;
  imported_ids jsonb := '[]'::jsonb;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  suite_payload := payload->'suite';

  insert into public.ielts_test_suites(
    slug,title,description,source_filename,status,created_by,metadata,updated_at
  )
  values(
    suite_payload->>'slug',
    suite_payload->>'title',
    suite_payload->>'description',
    suite_payload->>'source_filename',
    coalesce(suite_payload->>'status','draft'),
    auth.uid(),
    coalesce(suite_payload,'{}'::jsonb),
    now()
  )
  on conflict(slug) do update set
    title=excluded.title,
    description=excluded.description,
    source_filename=excluded.source_filename,
    status=excluded.status,
    metadata=excluded.metadata,
    updated_at=now()
  returning id into suite_pk;

  for paper_payload in
    select * from jsonb_array_elements(payload->'papers')
  loop
    paper_pk := public.import_ielts_paper_json(paper_payload);

    update public.ielts_papers
    set
      suite_id=suite_pk,
      status=coalesce(paper_payload->'metadata'->>'status','draft'),
      created_by=auth.uid(),
      is_published=(coalesce(paper_payload->'metadata'->>'status','draft')='published')
    where id=paper_pk;

    imported_ids := imported_ids || jsonb_build_array(paper_pk);
  end loop;

  return jsonb_build_object(
    'success',true,
    'suite_id',suite_pk,
    'paper_ids',imported_ids,
    'paper_count',jsonb_array_length(payload->'papers')
  );
end;
$$;

create or replace function public.admin_publish_ielts_suite(p_suite_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  incomplete_answers int;
  incomplete_audio int;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  select count(*) into incomplete_answers
  from public.ielts_items i
  join public.ielts_sections s on s.id=i.section_id
  join public.ielts_papers p on p.id=s.paper_id
  where p.suite_id=p_suite_id
    and p.module in ('reading','listening')
    and i.correct_answer is null;

  select count(*) into incomplete_audio
  from public.ielts_sections s
  join public.ielts_papers p on p.id=s.paper_id
  where p.suite_id=p_suite_id
    and p.module='listening'
    and coalesce(s.audio_url,'')='';

  if incomplete_answers > 0 or incomplete_audio > 0 then
    return jsonb_build_object(
      'success',false,
      'missing_answers',incomplete_answers,
      'missing_audio_sections',incomplete_audio,
      'message','Complete answer keys and listening audio before publishing.'
    );
  end if;

  update public.ielts_test_suites
  set status='published',updated_at=now()
  where id=p_suite_id;

  update public.ielts_papers
  set status='published',is_published=true
  where suite_id=p_suite_id;

  return jsonb_build_object('success',true,'suite_id',p_suite_id);
end;
$$;

alter table public.ielts_test_suites enable row level security;

drop policy if exists "read published test suites" on public.ielts_test_suites;
create policy "read published test suites"
on public.ielts_test_suites for select
using(status='published' or public.is_admin());

drop policy if exists "admin manages test suites" on public.ielts_test_suites;
create policy "admin manages test suites"
on public.ielts_test_suites for all
using(public.is_admin())
with check(public.is_admin());

drop policy if exists "published papers" on public.ielts_papers;
create policy "published or admin papers"
on public.ielts_papers for select
using((is_published=true and status='published') or public.is_admin());

create policy "admin manages papers"
on public.ielts_papers for all
using(public.is_admin())
with check(public.is_admin());

create policy "admin manages sections"
on public.ielts_sections for all
using(public.is_admin())
with check(public.is_admin());

create policy "admin manages items"
on public.ielts_items for all
using(public.is_admin())
with check(public.is_admin());

grant execute on function public.is_admin() to authenticated;
grant execute on function public.admin_import_ielts_bundle_json(jsonb) to authenticated;
grant execute on function public.admin_publish_ielts_suite(bigint) to authenticated;

notify pgrst,'reload schema';
