const stages=["Starter Foundations","Essential English","Everyday Communication","Independent English","IELTS Core Skills","Academic Development","Confident IELTS User","Advanced IELTS Skills","Band 7.5 Performance","Road to IELTS 8.0"];
const cefr=["Pre-A1","A1","A2","B1","B1+","B2","B2+","C1","C1+","IELTS 8.0"];
const titles=["Introducing Yourself","Personal Information","Family and Relationships","Daily Routines","Food and Lifestyle","Home and Community","Study and Work","Travel and Experiences","Communication Skills"];
const titlesVi=["Giới thiệu bản thân","Thông tin cá nhân","Gia đình và các mối quan hệ","Thói quen hằng ngày","Ẩm thực và lối sống","Nhà ở và cộng đồng","Học tập và công việc","Du lịch và trải nghiệm","Kỹ năng giao tiếp"];
export const demoLessons=Array.from({length:100},(_,i)=>{const n=i+1,s=Math.ceil(n/10),cp=n%10===0;return{id:n,level_number:n,slug:`level-${n}`,title:cp?`Stage ${s} Checkpoint`:titles[i%10],title_vi:cp?`Bài kiểm tra Chặng ${s}`:titlesVi[i%10],subtitle:"Build practical English through guided, interactive activities.",subtitle_vi:"Phát triển tiếng Anh thực tế qua các hoạt động tương tác có hướng dẫn.",stage_number:s,stage_name:stages[s-1],cefr_level:cefr[s-1],estimated_minutes:cp?40:25,xp_reward:cp?150:80+(i%5)*10,is_checkpoint:cp,is_published:true}});
export const demoLevelOne={...demoLessons[0],sections:[
{section_type:"overview",title:"What you will learn",title_vi:"Bạn sẽ học gì",instructions:"Complete each section before the checkpoint.",content:{objectives:["Use common greetings appropriately.","Introduce yourself using simple sentences.","Ask and answer basic personal questions.","Recognise key information in a short conversation."],objectives_vi:["Sử dụng các câu chào hỏi phổ biến.","Giới thiệu bản thân bằng câu đơn giản.","Hỏi và trả lời thông tin cá nhân cơ bản.","Nhận biết thông tin chính trong hội thoại ngắn."]}},
{section_type:"vocabulary",title:"Build your word bank",title_vi:"Xây dựng vốn từ",content:{items:[
{word:"hello",pronunciation:"/həˈləʊ/",meaning:"a greeting used when meeting someone",meaning_vi:"lời chào khi gặp ai đó",example:"Hello, my name is Anna."},
{word:"name",pronunciation:"/neɪm/",meaning:"the word used to identify a person",meaning_vi:"tên dùng để nhận diện một người",example:"My name is Daniel."},
{word:"from",pronunciation:"/frɒm/",meaning:"used to show where someone comes from",meaning_vi:"dùng để nói ai đó đến từ đâu",example:"I am from Vietnam."},
{word:"live",pronunciation:"/lɪv/",meaning:"to have your home in a place",meaning_vi:"sinh sống tại một nơi",example:"I live in Ho Chi Minh City."},
{word:"meet",pronunciation:"/miːt/",meaning:"to see someone for the first time",meaning_vi:"gặp ai đó lần đầu",example:"Nice to meet you."},
{word:"student",pronunciation:"/ˈstjuːdənt/",meaning:"a person who studies",meaning_vi:"người đang học",example:"I am a student."}]}},
{section_type:"grammar",title:"The verb be: I am and You are",title_vi:"Động từ be: I am và You are",content:{explanation:"Use “I am” to give information about yourself.",explanation_vi:"Dùng “I am” để nói về bản thân.",formula:["I + am + information","You + are + information","My name + is + name"],examples:["I am Minh.","I’m from Vietnam.","You are a student.","My name is Emma."]}},
{section_type:"reading",title:"Meet Daniel",title_vi:"Làm quen với Daniel",content:{passage:"Hello! My name is Daniel. I am 19 years old. I am from Australia, but I live in Singapore. I am a university student. I study business. I enjoy football and music.",questions:[{question:"How old is Daniel?",answer:"19"},{question:"Where does Daniel live?",answer:"Singapore"},{question:"What does Daniel study?",answer:"Business"}]}},
{section_type:"listening",title:"Meeting a new classmate",title_vi:"Gặp một bạn học mới",instructions:"Listen twice and complete the dictation.",content:{transcript:"Hello! My name is Mia. I am from Brazil, but I live in London now.",exercises:[{type:"dictation",prompt:"Type the first sentence you hear.",answer:"Hello! My name is Mia."}]}},
{section_type:"speaking",title:"Introduce yourself",title_vi:"Tự giới thiệu",content:{prompts:["What is your name?","Where are you from?","Where do you live?","What do you enjoy doing?"],model_answer:"Hello, my name is Anna. I am from Thailand, and I live in Bangkok. I enjoy reading and listening to music."}},
{section_type:"writing",title:"Write a personal introduction",title_vi:"Viết đoạn giới thiệu bản thân",content:{prompt:"Write four to six sentences. Include your name, hometown, current city, study or job and one interest.",checklist:["Use capital letters.","Use full stops.","Use I am or I’m.","Write at least four sentences."]}},
{section_type:"quiz",title:"Level checkpoint",title_vi:"Bài kiểm tra cuối cấp độ",content:{exercises:[
{type:"multiple_choice",prompt:"Choose the correct sentence.",options:["I is Minh.","I am Minh.","I are Minh."],answer:"I am Minh.",explanation:"Use am after the subject I."},
{type:"fill_blank",prompt:"Complete: My name ___ Sarah.",answer:"is",explanation:"Use is after my name."},
{type:"matching",prompt:"Match the greeting with the natural response.",pairs:[["Hello!","Hi!"],["Nice to meet you.","Nice to meet you too."],["How are you?","I’m fine, thanks."]]},
{type:"ordering",prompt:"Put the words in the correct order.",items:["from","I","Vietnam","am"],answer:["I","am","from","Vietnam"]}]}}
]};
export const ieltsModules=[["listening","IELTS Listening","Audio, dictation, form completion and multiple choice."],["reading","IELTS Reading","Skimming, scanning, headings and True/False/Not Given."],["writing","IELTS Writing","Task 1 and Task 2 planning and drafting."],["speaking","IELTS Speaking","Part 1, cue cards, Part 3 and recording practice."]].map(([slug,title,description],i)=>({slug,title,title_vi:title,description,description_vi:description,tasks:[12,18,10,14][i]}));
