create extension if not exists pgcrypto;

-- =========================================================
-- CORE USERS
-- =========================================================
create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'learner'
    check(role in ('learner','teacher','admin','founder')),
  target_band numeric(2,1) default 8.0,
  daily_minutes int default 30,
  current_lesson int default 1,
  total_xp int default 0,
  coins int default 0,
  hearts int default 5,
  streak_days int default 0,
  placement_completed boolean default false,
  onboarding_completed boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.profiles add column if not exists role text not null default 'learner';

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(id,full_name)
  values(
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1))
  )
  on conflict(id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.profiles
    where id=auth.uid() and role in ('admin','founder')
  );
$$;

-- =========================================================
-- LEARNING ENGINE
-- =========================================================
create table if not exists public.courses(
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  title_vi text,
  description text,
  description_vi text,
  is_published boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.lessons(
  id bigint generated by default as identity primary key,
  course_id bigint references public.courses(id) on delete cascade,
  level_number int unique not null check(level_number between 1 and 100),
  slug text unique not null,
  title text not null,
  title_vi text,
  subtitle text,
  subtitle_vi text,
  stage_number int not null,
  stage_name text not null,
  cefr_level text not null,
  xp_reward int default 100,
  coin_reward int default 20,
  estimated_minutes int default 40,
  is_checkpoint boolean default false,
  is_published boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.lesson_blocks(
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  block_type text not null,
  title text,
  title_vi text,
  instructions text,
  instructions_vi text,
  content jsonb not null default '{}'::jsonb,
  position int not null default 0,
  is_required boolean default true,
  is_published boolean default true,
  unique(lesson_id,position)
);

create table if not exists public.user_progress(
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  level_id int not null,
  completed boolean default false,
  score numeric(5,2),
  earned_xp int default 0,
  earned_coins int default 0,
  completed_at timestamptz,
  updated_at timestamptz default now(),
  unique(user_id,level_id)
);

create table if not exists public.game_sessions(
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  game_slug text not null,
  level_number int,
  score int default 0,
  gates_passed int default 0,
  questions_answered int default 0,
  correct_answers int default 0,
  xp_earned int default 0,
  coins_earned int default 0,
  created_at timestamptz default now()
);

create or replace function public.complete_lesson(
  p_level_number int,
  p_score numeric default 100
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid:=auth.uid();
  reward int;
  coin int;
  was_done boolean;
begin
  if uid is null then raise exception 'Not authenticated'; end if;

  select xp_reward,coin_reward
  into reward,coin
  from public.lessons
  where level_number=p_level_number and is_published=true;

  if reward is null then raise exception 'Lesson not found'; end if;

  select completed into was_done
  from public.user_progress
  where user_id=uid and level_id=p_level_number;

  was_done:=coalesce(was_done,false);

  insert into public.user_progress(
    user_id,level_id,completed,score,earned_xp,earned_coins,completed_at,updated_at
  )
  values(
    uid,p_level_number,true,p_score,
    case when was_done then 0 else reward end,
    case when was_done then 0 else coin end,
    now(),now()
  )
  on conflict(user_id,level_id)
  do update set
    completed=true,
    score=excluded.score,
    updated_at=now();

  update public.profiles
  set
    current_lesson=greatest(current_lesson,least(p_level_number+1,100)),
    total_xp=total_xp+case when was_done then 0 else reward end,
    coins=coins+case when was_done then 0 else coin end,
    updated_at=now()
  where id=uid;

  return jsonb_build_object(
    'success',true,
    'xp_awarded',case when was_done then 0 else reward end,
    'coins_awarded',case when was_done then 0 else coin end
  );
end;
$$;

-- =========================================================
-- PLACEMENT / QUESTION BANK
-- =========================================================
create table if not exists public.question_banks(
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  purpose text,
  tags text[] default '{}',
  created_at timestamptz default now()
);

create table if not exists public.questions(
  id bigint generated by default as identity primary key,
  bank_id bigint references public.question_banks(id) on delete cascade,
  question_type text not null,
  skill text,
  difficulty int default 1,
  prompt text not null,
  prompt_vi text,
  options jsonb default '[]'::jsonb,
  correct_answer jsonb,
  explanation text,
  explanation_vi text,
  audio_url text,
  audio_text text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.placement_blueprints(
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  config jsonb not null,
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.placement_attempts(
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  score int,
  total_questions int,
  recommended_level int,
  estimated_cefr text,
  estimated_ielts text,
  skill_profile jsonb default '{}'::jsonb,
  answers jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- =========================================================
-- IELTS CMS / TEST ENGINE
-- =========================================================
create table if not exists public.ielts_test_suites(
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  source_filename text,
  status text not null default 'draft'
    check(status in ('draft','review','published','archived')),
  created_by uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ielts_papers(
  id bigint generated by default as identity primary key,
  suite_id bigint references public.ielts_test_suites(id) on delete cascade,
  slug text unique not null,
  title text not null,
  module text not null check(module in ('reading','listening','writing','speaking')),
  test_type text default 'academic',
  duration_minutes int not null,
  instructions text,
  metadata jsonb default '{}'::jsonb,
  status text not null default 'draft'
    check(status in ('draft','review','published','archived')),
  is_published boolean default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ielts_sections(
  id bigint generated by default as identity primary key,
  paper_id bigint not null references public.ielts_papers(id) on delete cascade,
  section_number int not null,
  title text,
  passage text,
  audio_url text,
  transcript text,
  instructions text,
  metadata jsonb default '{}'::jsonb,
  unique(paper_id,section_number)
);

create table if not exists public.ielts_items(
  id bigint generated by default as identity primary key,
  section_id bigint not null references public.ielts_sections(id) on delete cascade,
  item_number int not null,
  question_type text not null,
  prompt text not null,
  options jsonb default '[]'::jsonb,
  correct_answer jsonb,
  explanation text,
  metadata jsonb default '{}'::jsonb,
  unique(section_id,item_number)
);

create table if not exists public.ielts_attempts(
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  paper_id bigint references public.ielts_papers(id) on delete cascade,
  answers jsonb default '{}'::jsonb,
  flagged_items jsonb default '[]'::jsonb,
  section_times jsonb default '{}'::jsonb,
  score numeric(5,2),
  raw_score int,
  total_items int,
  status text default 'in_progress'
    check(status in ('in_progress','submitted','reviewed')),
  started_at timestamptz default now(),
  submitted_at timestamptz,
  updated_at timestamptz default now()
);

-- Import one paper. Accepts sections/questions or question_groups.
create or replace function public.import_ielts_paper_json(
  payload jsonb,
  p_suite_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare
  paper_pk bigint;
  section_pk bigint;
  s jsonb;
  g jsonb;
  q jsonb;
  sn int:=0;
  qn int:=0;
  questions_array jsonb;
  answer_payload jsonb;
begin
  insert into public.ielts_papers(
    suite_id,slug,title,module,test_type,duration_minutes,
    instructions,metadata,status,is_published,created_by,updated_at
  )
  values(
    p_suite_id,
    payload->>'slug',
    payload->>'title',
    payload->>'module',
    coalesce(payload->>'test_type','academic'),
    coalesce((payload->>'duration_minutes')::int,60),
    payload->>'instructions',
    coalesce(payload->'metadata','{}'::jsonb),
    coalesce(payload->'metadata'->>'status','draft'),
    coalesce(payload->'metadata'->>'status','draft')='published',
    auth.uid(),
    now()
  )
  on conflict(slug) do update set
    suite_id=excluded.suite_id,
    title=excluded.title,
    module=excluded.module,
    test_type=excluded.test_type,
    duration_minutes=excluded.duration_minutes,
    instructions=excluded.instructions,
    metadata=excluded.metadata,
    status=excluded.status,
    is_published=excluded.is_published,
    updated_at=now()
  returning id into paper_pk;

  delete from public.ielts_sections where paper_id=paper_pk;

  for s in select * from jsonb_array_elements(coalesce(payload->'sections','[]'::jsonb))
  loop
    sn:=sn+1;

    insert into public.ielts_sections(
      paper_id,section_number,title,passage,audio_url,transcript,instructions,metadata
    )
    values(
      paper_pk,
      coalesce((s->>'section_number')::int,sn),
      s->>'title',
      s->>'passage',
      s->>'audio_url',
      s->>'transcript',
      s->>'instructions',
      coalesce(s->'metadata','{}'::jsonb)
    )
    returning id into section_pk;

    qn:=0;

    if jsonb_typeof(s->'questions')='array' then
      questions_array:=s->'questions';
    elsif jsonb_typeof(s->'question_groups')='array' then
      questions_array:='[]'::jsonb;
      for g in select * from jsonb_array_elements(s->'question_groups')
      loop
        for q in select * from jsonb_array_elements(coalesce(g->'questions','[]'::jsonb))
        loop
          questions_array:=questions_array || jsonb_build_array(
            q || jsonb_build_object(
              'type',coalesce(q->>'type',g->>'type'),
              'group_instructions',g->>'instructions',
              'group_options',g->'options',
              'group_prompt',g->>'prompt'
            )
          );
        end loop;
      end loop;
    else
      questions_array:='[]'::jsonb;
    end if;

    for q in select * from jsonb_array_elements(questions_array)
    loop
      qn:=qn+1;
      answer_payload:=case
        when q ? 'answer' then q->'answer'
        else null
      end;

      insert into public.ielts_items(
        section_id,item_number,question_type,prompt,options,
        correct_answer,explanation,metadata
      )
      values(
        section_pk,
        coalesce((q->>'number')::int,qn),
        coalesce(q->>'type',q->>'question_type','short_answer'),
        coalesce(q->>'prompt',q->>'question',''),
        case
          when jsonb_typeof(q->'options') is not null then q->'options'
          when jsonb_typeof(q->'group_options') is not null then q->'group_options'
          else '[]'::jsonb
        end,
        answer_payload,
        q->>'explanation',
        coalesce(q->'metadata','{}'::jsonb)
          || jsonb_build_object(
            'group_instructions',q->>'group_instructions',
            'group_prompt',q->>'group_prompt'
          )
      );
    end loop;
  end loop;

  return paper_pk;
end;
$$;

-- Accepts either:
-- {suite:{...}, papers:[...]}
-- or {suite:{...}, paper:{...}}
create or replace function public.admin_import_ielts_bundle_json(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  suite_payload jsonb;
  paper_payload jsonb;
  papers_payload jsonb;
  suite_pk bigint;
  paper_pk bigint;
  imported_ids jsonb:='[]'::jsonb;
  paper_count int:=0;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  if payload->'suite' is null then
    raise exception 'Missing suite object';
  end if;

  if jsonb_typeof(payload->'papers')='array' then
    papers_payload:=payload->'papers';
  elsif payload->'paper' is not null then
    papers_payload:=jsonb_build_array(payload->'paper');
  else
    raise exception 'Missing paper or papers';
  end if;

  suite_payload:=payload->'suite';

  insert into public.ielts_test_suites(
    slug,title,description,source_filename,status,created_by,metadata,updated_at
  )
  values(
    suite_payload->>'slug',
    suite_payload->>'title',
    suite_payload->>'description',
    suite_payload->>'source_file',
    coalesce(suite_payload->>'status','draft'),
    auth.uid(),
    coalesce(suite_payload,'{}'::jsonb),
    now()
  )
  on conflict(slug) do update set
    title=excluded.title,
    description=excluded.description,
    source_filename=excluded.source_filename,
    status=excluded.status,
    metadata=excluded.metadata,
    updated_at=now()
  returning id into suite_pk;

  for paper_payload in select * from jsonb_array_elements(papers_payload)
  loop
    -- Normalize V3 single reading paper format.
    if paper_payload->>'slug' is null then
      paper_payload:=paper_payload || jsonb_build_object(
        'slug',coalesce(
          suite_payload->>'slug',
          regexp_replace(lower(paper_payload->>'title'),'[^a-z0-9]+','-','g')
        ),
        'module',coalesce(suite_payload->>'module','reading'),
        'test_type',coalesce(suite_payload->>'type','academic'),
        'duration_minutes',coalesce(
          (suite_payload->>'duration_minutes')::int,
          (suite_payload->>'duration')::int,
          60
        ),
        'metadata',jsonb_build_object(
          'status',coalesce(suite_payload->>'status','draft')
        )
      );
    end if;

    paper_pk:=public.import_ielts_paper_json(paper_payload,suite_pk);
    imported_ids:=imported_ids || jsonb_build_array(paper_pk);
    paper_count:=paper_count+1;
  end loop;

  return jsonb_build_object(
    'success',true,
    'suite_id',suite_pk,
    'paper_ids',imported_ids,
    'paper_count',paper_count
  );
end;
$$;

create or replace function public.save_ielts_attempt(
  p_paper_id bigint,
  p_answers jsonb,
  p_flagged_items jsonb default '[]'::jsonb,
  p_section_times jsonb default '{}'::jsonb,
  p_submit boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid:=auth.uid();
  attempt_pk bigint;
  item_record record;
  supplied jsonb;
  correct_count int:=0;
  total_count int:=0;
  score_value numeric(5,2);
begin
  if uid is null then raise exception 'Not authenticated'; end if;

  for item_record in
    select i.id,i.item_number,i.correct_answer
    from public.ielts_items i
    join public.ielts_sections s on s.id=i.section_id
    where s.paper_id=p_paper_id
  loop
    total_count:=total_count+1;
    supplied:=p_answers->(item_record.item_number::text);

    if item_record.correct_answer is not null
       and lower(trim(both '"' from supplied::text))
           = lower(trim(both '"' from item_record.correct_answer::text))
    then
      correct_count:=correct_count+1;
    end if;
  end loop;

  score_value:=case when total_count>0
    then round(correct_count::numeric*100/total_count,2)
    else null end;

  insert into public.ielts_attempts(
    user_id,paper_id,answers,flagged_items,section_times,
    score,raw_score,total_items,status,submitted_at,updated_at
  )
  values(
    uid,p_paper_id,coalesce(p_answers,'{}'::jsonb),
    coalesce(p_flagged_items,'[]'::jsonb),
    coalesce(p_section_times,'{}'::jsonb),
    score_value,correct_count,total_count,
    case when p_submit then 'submitted' else 'in_progress' end,
    case when p_submit then now() else null end,
    now()
  )
  returning id into attempt_pk;

  return jsonb_build_object(
    'success',true,
    'attempt_id',attempt_pk,
    'raw_score',correct_count,
    'total_items',total_count,
    'score_percent',score_value
  );
end;
$$;

create or replace function public.admin_publish_ielts_suite(p_suite_id bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  incomplete_answers int;
  incomplete_audio int;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  select count(*) into incomplete_answers
  from public.ielts_items i
  join public.ielts_sections s on s.id=i.section_id
  join public.ielts_papers p on p.id=s.paper_id
  where p.suite_id=p_suite_id
    and p.module in ('reading','listening')
    and i.correct_answer is null;

  select count(*) into incomplete_audio
  from public.ielts_sections s
  join public.ielts_papers p on p.id=s.paper_id
  where p.suite_id=p_suite_id
    and p.module='listening'
    and coalesce(s.audio_url,'')='';

  if incomplete_answers>0 or incomplete_audio>0 then
    return jsonb_build_object(
      'success',false,
      'missing_answers',incomplete_answers,
      'missing_audio_sections',incomplete_audio,
      'message','Complete answer keys and Listening audio before publishing.'
    );
  end if;

  update public.ielts_test_suites
  set status='published',updated_at=now()
  where id=p_suite_id;

  update public.ielts_papers
  set status='published',is_published=true,updated_at=now()
  where suite_id=p_suite_id;

  return jsonb_build_object('success',true,'suite_id',p_suite_id);
end;
$$;

-- =========================================================
-- RLS
-- =========================================================
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.lesson_blocks enable row level security;
alter table public.user_progress enable row level security;
alter table public.game_sessions enable row level security;
alter table public.question_banks enable row level security;
alter table public.questions enable row level security;
alter table public.placement_blueprints enable row level security;
alter table public.placement_attempts enable row level security;
alter table public.ielts_test_suites enable row level security;
alter table public.ielts_papers enable row level security;
alter table public.ielts_sections enable row level security;
alter table public.ielts_items enable row level security;
alter table public.ielts_attempts enable row level security;

drop policy if exists "own profile" on public.profiles;
create policy "own profile" on public.profiles
for all using(auth.uid()=id) with check(auth.uid()=id);

drop policy if exists "published courses" on public.courses;
create policy "published courses" on public.courses
for select using(is_published=true or public.is_admin());

drop policy if exists "published lessons" on public.lessons;
create policy "published lessons" on public.lessons
for select using(is_published=true or public.is_admin());

drop policy if exists "published blocks" on public.lesson_blocks;
create policy "published blocks" on public.lesson_blocks
for select using(is_published=true or public.is_admin());

drop policy if exists "own progress" on public.user_progress;
create policy "own progress" on public.user_progress
for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

drop policy if exists "own games" on public.game_sessions;
create policy "own games" on public.game_sessions
for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

drop policy if exists "read question banks" on public.question_banks;
create policy "read question banks" on public.question_banks
for select using(true);

drop policy if exists "read questions" on public.questions;
create policy "read questions" on public.questions
for select using(true);

drop policy if exists "read placement blueprint" on public.placement_blueprints;
create policy "read placement blueprint" on public.placement_blueprints
for select using(is_active=true);

drop policy if exists "own placement attempts" on public.placement_attempts;
create policy "own placement attempts" on public.placement_attempts
for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

drop policy if exists "read suites" on public.ielts_test_suites;
create policy "read suites" on public.ielts_test_suites
for select using(status='published' or public.is_admin());

drop policy if exists "admin suites" on public.ielts_test_suites;
create policy "admin suites" on public.ielts_test_suites
for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "read papers" on public.ielts_papers;
create policy "read papers" on public.ielts_papers
for select using((is_published=true and status='published') or public.is_admin());

drop policy if exists "admin papers" on public.ielts_papers;
create policy "admin papers" on public.ielts_papers
for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "read sections" on public.ielts_sections;
create policy "read sections" on public.ielts_sections
for select using(
  exists(
    select 1 from public.ielts_papers p
    where p.id=paper_id
      and ((p.is_published=true and p.status='published') or public.is_admin())
  )
);

drop policy if exists "admin sections" on public.ielts_sections;
create policy "admin sections" on public.ielts_sections
for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "read items" on public.ielts_items;
create policy "read items" on public.ielts_items
for select using(
  exists(
    select 1
    from public.ielts_sections s
    join public.ielts_papers p on p.id=s.paper_id
    where s.id=section_id
      and ((p.is_published=true and p.status='published') or public.is_admin())
  )
);

drop policy if exists "admin items" on public.ielts_items;
create policy "admin items" on public.ielts_items
for all using(public.is_admin()) with check(public.is_admin());

drop policy if exists "own ielts attempts" on public.ielts_attempts;
create policy "own ielts attempts" on public.ielts_attempts
for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

grant execute on function public.is_admin() to authenticated;
grant execute on function public.complete_lesson(int,numeric) to authenticated;
grant execute on function public.admin_import_ielts_bundle_json(jsonb) to authenticated;
grant execute on function public.admin_publish_ielts_suite(bigint) to authenticated;
grant execute on function public.save_ielts_attempt(bigint,jsonb,jsonb,jsonb,boolean) to authenticated;

notify pgrst,'reload schema';
