create table if not exists public.course_modules(
 id bigint generated by default as identity primary key,
 course_id bigint not null references public.courses(id) on delete cascade,
 title text not null,title_vi text,position int not null default 0,
 is_published boolean default false,created_at timestamptz default now()
);

create table if not exists public.assignments(
 id bigint generated by default as identity primary key,
 course_id bigint references public.courses(id) on delete cascade,
 lesson_id bigint references public.lessons(id) on delete set null,
 title text not null,description text,instructions jsonb default '{}'::jsonb,
 due_at timestamptz,max_score numeric default 100,status text default 'draft',
 created_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now()
);

create table if not exists public.assignment_submissions(
 id bigint generated by default as identity primary key,
 assignment_id bigint not null references public.assignments(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 content jsonb default '{}'::jsonb,file_url text,status text default 'submitted',
 score numeric,feedback text,submitted_at timestamptz default now(),reviewed_at timestamptz,
 unique(assignment_id,user_id)
);

create table if not exists public.support_tickets(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 subject text not null,category text default 'learning',
 priority text default 'normal',status text default 'open',
 lesson_id bigint references public.lessons(id) on delete set null,
 assigned_to uuid references auth.users(id) on delete set null,
 created_at timestamptz default now(),updated_at timestamptz default now()
);

create table if not exists public.support_messages(
 id bigint generated by default as identity primary key,
 ticket_id bigint not null references public.support_tickets(id) on delete cascade,
 sender_id uuid not null references auth.users(id) on delete cascade,
 message text not null,attachment_url text,is_internal boolean default false,
 created_at timestamptz default now()
);

create table if not exists public.content_feedback(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 lesson_id bigint references public.lessons(id) on delete cascade,
 item_reference text,rating int check(rating between 1 and 5),
 feedback text,status text default 'new',
 created_at timestamptz default now(),resolved_at timestamptz
);

alter table public.course_modules enable row level security;
alter table public.assignments enable row level security;
alter table public.assignment_submissions enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;
alter table public.content_feedback enable row level security;

create policy "published modules" on public.course_modules for select using(is_published=true or public.is_admin());
create policy "admin modules" on public.course_modules for all using(public.is_admin()) with check(public.is_admin());

create policy "published assignments" on public.assignments for select using(status='published' or public.is_admin());
create policy "admin assignments" on public.assignments for all using(public.is_admin()) with check(public.is_admin());

create policy "own submissions" on public.assignment_submissions for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());

create policy "own tickets" on public.support_tickets for select using(user_id=auth.uid() or public.is_admin());
create policy "create own tickets" on public.support_tickets for insert with check(user_id=auth.uid());
create policy "admin ticket updates" on public.support_tickets for update using(public.is_admin());

create policy "ticket messages" on public.support_messages for select using(
 public.is_admin() or exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=auth.uid())
);
create policy "send ticket messages" on public.support_messages for insert with check(
 sender_id=auth.uid() and (
 public.is_admin() or exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=auth.uid())
 )
);

create policy "own feedback" on public.content_feedback for insert with check(user_id=auth.uid());
create policy "view own feedback" on public.content_feedback for select using(user_id=auth.uid() or public.is_admin());
create policy "admin feedback" on public.content_feedback for update using(public.is_admin());

notify pgrst,'reload schema';
